# Generated by Django 6.0.1 on 2026-02-01 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('sys_id', models.TextField(primary_key=True, serialize=False)),
                ('u_sso_id_name', models.TextField(blank=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('sys_updated_on', models.DateField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='OriDB.record')),
            ],
            options={
                'db_table': 'record',
                'indexes': [models.Index(fields=['parent'], name='record_parent_bace79_idx'), models.Index(fields=['sys_updated_on'], name='record_sys_upd_d83a41_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sys_id', models.F('parent')), _negated=True), name='record_parent_not_self')],
            },
        ),
    ]
