# Generated by Django 6.0.1 on 2026-02-02 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OriDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField()),
                ('date', models.DateField()),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('record', models.ForeignKey(db_column='record', on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='OriDB.record')),
            ],
            options={
                'db_table': 'customer_meeting',
                'indexes': [models.Index(fields=['record'], name='customer_me_record_9807cb_idx'), models.Index(fields=['date'], name='customer_me_date_9fa090_idx')],
            },
        ),
    ]
